#
# This file contains configuration flags to customize your site
#

# --- Basic options --- #

# Name of your site (displayed in the header)
title: IMPORT YOUR IDEAS
name: IMPORT YOUR IDEAS
# Short bio or description (displayed in the header)
description: >-                        # used by seo meta and the atom feed
  Entusiasta de la vida y Tecnófilo a ratos.
  Tecnicamente Desarrollador en Big DATA e Inteligencia Artificial.
# Your name to show in the footer
author: Victor Quilón Ranera


# --- Logo --- #

# Image to show in the navigation bar - works best with a square image
# Remove this parameter if you don't want an image in the navbar

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: /assets/img/iyi_b_v2.png
round-avatar: true

# If you want to have an image logo in the top-left corner instead of the title text,
# then specify the following parameter
#title-img: /assets/img/iyi_b_v2.png


# --- Misc --- #

# Character used to separate site title and description in HTML document title
# and RSS feed title
title-separator: "-"

# format of URL of your posts
permalink: /:title/

# Ruby Date Format to show dates of posts
date_format: "%B %-d, %Y"

# Facebook App ID
#fb_app_id: ""


# --- Footer --- #
# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: "v.quilonr@gmail.com"
  facebook:
  flickr:
  github: import-your-ideas/import-your-ideas.github.io
  instagram:
  linkedin: 
  pinterest:
  rss: # just type anything here for a working RSS icon
  twitter:
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  # googleplus: # anything in your profile username that comes after plus.google.com/


# --- Web Statistics Section --- #

# Fill in your Google Analytics gtag.js ID to track your website using gtag
#gtag: ""

# Fill in your Google Analytics ID to track your website using GA
#google_analytics: ""

# Google Tag Manager ID
#gtm: ""

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: http://import-your-ideas.github.io

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""


# Matomo (aka Piwik) Web statistics
# Uncomment the following section to enable Matomo. The opt-out parameter controls
# whether or not you want to allow users to opt out of tracking.
#matomo:
#  site_id: "9"
#  uri: "demo.wiki.pro"
#  opt-out: true



# --- Comments --- #
# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
# To use Disqus comments, sign up to https://disqus.com and fill in your Disqus shortname (NOT the userid)
# disqus: ""

# To use Facebook Comments, create a Facebook app and fill in the Facebook App ID
#fb_comment_id: ""


# --- You don't need to touch anything below here (but you can if you want) --- #
# --- Config --- #
# The release of Jekyll Now that you're using
version: v4.0.1

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed


# Use the following plug-ins
plugins:
  - "jekyll-github-metadata"
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

theme: jekyll-theme-cayman